### ISSUE TITLE
db load not contabilized due only mysql

### ISSUE THREAD

**Issue by mckaygerhard** [CNRS-DSI-Dev/mycore_press#1]
i read the papers of the project, and have a great error in deploy

the db choosen was MariaDB/MySQL and that's why the workload are not enought and got some deadlocks (not present at the papers but obviously)

in my implementation (ironically parallel) i used postgresql with some db pooling features..  no deadlock happened, and this was an knowed issue in owncloud.. 

today we migrated to nextcloud and the same problem.. better choose postgresql .. a real db.. so the desktops app and mobile apps can interact without problems-

**Comment by ppaysant** [comment]
Great, thanks for your tip.
